FROM rmohr/activemq:latest

USER root

RUN apt-get update
RUN apt-get install -y vim
RUN apt-get install -y tcpdump
RUN apt-get install -y net-tools
RUN apt-get install -y curl
RUN apt-get install -y nmap

USER activemq